<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> -->

    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 p-5 bg-light">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                
                <form action="/urls" method="post" class="rss-form d-flex justify-content-center align-items-start">
                    <div class="w-100">
                        <input type="text" 
                            name="url[name]" 
                            class="form-control form-control-lg <?= isset($errors['name']) ? 'is-invalid' : '' ?>" 
                            placeholder="https://www.example.com"
                            value="<?= htmlspecialchars($url['name'] ?? '') ?>">
                        
                        <?php if (isset($errors['name'])): ?>
                            <div class="invalid-feedback">
                                <?= $errors['name'] ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <button type="submit" class="btn btn-lg btn-primary ms-3 px-5 text-uppercase">Проверить</button>
                </form>
            </div>
        </div>
    </div>

    <!-- <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://ru.hexlet.io" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer> -->
</body>
</html>