<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 p-5 bg-light">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                
                <form action="/urls" method="post" class="rss-form d-flex justify-content-center align-items-start">
                    <div class="w-100">
                        <input type="text" 
                            name="url[name]" 
                            class="form-control form-control-lg <?= isset($errors['name']) ? 'is-invalid' : '' ?>" 
                            placeholder="https://www.example.com"
                            value="<?= htmlspecialchars($url['name'] ?? '') ?>">
                        
                        <?php if (isset($errors['name'])): ?>
                            <div class="invalid-feedback">
                                <?= $errors['name'] ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <input type="submit" class="btn btn-lg btn-primary ms-3 px-5 text-uppercase" value="Проверить">
                </form>
            </div>
        </div>
    </div>
</body>
</html>